// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgInput_rows_val,
        imgInput_cols_val,
        in_mat_data_dout,
        in_mat_data_num_data_valid,
        in_mat_data_fifo_cap,
        in_mat_data_empty_n,
        in_mat_data_read,
        imgOutput_rows_val,
        imgOutput_cols_val,
        out_resize_mat_data_din,
        out_resize_mat_data_num_data_valid,
        out_resize_mat_data_fifo_cap,
        out_resize_mat_data_full_n,
        out_resize_mat_data_write
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] imgInput_rows_val;
input  [31:0] imgInput_cols_val;
input  [7:0] in_mat_data_dout;
input  [2:0] in_mat_data_num_data_valid;
input  [2:0] in_mat_data_fifo_cap;
input   in_mat_data_empty_n;
output   in_mat_data_read;
input  [31:0] imgOutput_rows_val;
input  [31:0] imgOutput_cols_val;
output  [7:0] out_resize_mat_data_din;
input  [2:0] out_resize_mat_data_num_data_valid;
input  [2:0] out_resize_mat_data_fifo_cap;
input   out_resize_mat_data_full_n;
output   out_resize_mat_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_mat_data_read;
reg out_resize_mat_data_write;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] trunc_ln310_fu_266_p1;
reg   [15:0] trunc_ln310_reg_832;
wire   [15:0] trunc_ln311_fu_270_p1;
reg   [15:0] trunc_ln311_reg_837;
wire   [32:0] tmp_fu_304_p3;
reg   [32:0] tmp_reg_842;
wire    ap_CS_fsm_state2;
wire   [63:0] xnew_fu_312_p3;
reg   [63:0] xnew_reg_847;
wire   [47:0] trunc_ln320_fu_320_p1;
reg   [47:0] trunc_ln320_reg_852;
wire    ap_CS_fsm_state3;
wire   [63:0] ynew_fu_324_p3;
reg   [63:0] ynew_reg_857;
wire   [47:0] trunc_ln323_fu_332_p1;
reg   [47:0] trunc_ln323_reg_862;
wire    ap_CS_fsm_state4;
wire   [31:0] loop_row_count_fu_340_p3;
reg   [31:0] loop_row_count_reg_867;
wire   [31:0] loop_col_count_fu_350_p3;
reg   [31:0] loop_col_count_reg_872;
wire   [31:0] sub302_fu_356_p2;
reg   [31:0] sub302_reg_877;
wire   [31:0] sub97_fu_361_p2;
reg   [31:0] sub97_reg_882;
reg   [21:0] shr_i_i_i_i102_cast_reg_887;
wire   [42:0] conv_i_i12_i530_i1_fu_386_p1;
reg   [42:0] conv_i_i12_i530_i1_reg_892;
wire   [53:0] shl_i_i_i_i396_i_fu_395_p3;
reg   [53:0] shl_i_i_i_i396_i_reg_897;
wire   [53:0] shl_i_i_i_i_i_fu_403_p3;
reg   [53:0] shl_i_i_i_i_i_reg_902;
wire   [41:0] indexx_pre_1_fu_415_p3;
reg   [41:0] indexx_pre_1_reg_907;
wire   [41:0] shl_i_i_i373_i_fu_427_p3;
reg   [41:0] shl_i_i_i373_i_reg_912;
wire   [0:0] slt_fu_462_p2;
reg   [0:0] slt_reg_923;
wire    ap_CS_fsm_state6;
wire   [41:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return;
reg  signed [41:0] indexy_pre_comp_reg_929;
wire    ap_CS_fsm_state12;
wire   [21:0] trunc_ln409_fu_467_p1;
reg   [21:0] trunc_ln409_reg_935;
reg   [16:0] tmp_cast_reg_940;
reg   [0:0] tmp_10_reg_946;
wire   [0:0] cmp_i_i398_i_fu_502_p2;
reg   [0:0] cmp_i_i398_i_reg_951;
wire   [0:0] cmp71_fu_510_p2;
reg   [0:0] cmp71_reg_959;
wire    ap_CS_fsm_state13;
wire   [31:0] sub_fu_515_p2;
reg   [31:0] sub_reg_967;
wire   [0:0] cmp308_fu_521_p2;
reg   [0:0] cmp308_reg_974;
wire   [31:0] sub309_fu_526_p2;
reg   [31:0] sub309_reg_980;
wire   [16:0] add_i_i_i_i_i475_i_fu_539_p2;
reg   [16:0] add_i_i_i_i_i475_i_reg_986;
wire   [21:0] empty_72_fu_557_p1;
reg   [21:0] empty_72_reg_991;
wire   [16:0] tmp_cast_73_fu_561_p4;
reg   [16:0] tmp_cast_73_reg_996;
reg   [0:0] tmp_12_reg_1001;
wire   [23:0] empty_74_fu_579_p1;
reg   [23:0] empty_74_reg_1006;
wire   [16:0] add_i_i_i_i_i349_i_fu_583_p2;
reg   [16:0] add_i_i_i_i_i349_i_reg_1011;
wire   [31:0] first_row_index_fu_601_p2;
reg   [31:0] first_row_index_reg_1025;
wire    ap_CS_fsm_state15;
reg   [6:0] line_buffer_address0;
reg    line_buffer_ce0;
reg    line_buffer_we0;
reg   [7:0] line_buffer_d0;
wire   [7:0] line_buffer_q0;
reg    line_buffer_ce1;
wire   [7:0] line_buffer_q1;
reg   [6:0] line_buffer_1_address0;
reg    line_buffer_1_ce0;
reg    line_buffer_1_we0;
reg   [7:0] line_buffer_1_d0;
wire   [7:0] line_buffer_1_q0;
reg    line_buffer_1_ce1;
wire   [7:0] line_buffer_1_q1;
wire   [7:0] line_buffer_2_q0;
wire   [7:0] line_buffer_2_q1;
wire    grp_xfUDivResize_fu_186_ap_start;
wire    grp_xfUDivResize_fu_186_ap_done;
wire    grp_xfUDivResize_fu_186_ap_idle;
wire    grp_xfUDivResize_fu_186_ap_ready;
reg   [63:0] grp_xfUDivResize_fu_186_in_n;
reg   [15:0] grp_xfUDivResize_fu_186_in_d;
wire   [63:0] grp_xfUDivResize_fu_186_ap_return;
reg   [31:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_203_currindex;
reg   [47:0] grp_scaleCompute_17_42_20_48_16_1_s_fu_203_inscale;
reg    grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_ce;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_done;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_idle;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_ready;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_in_mat_data_read;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_address0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_ce0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_we0;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_d0;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_address0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_ce0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_we0;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_d0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_done;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_idle;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_ready;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_in_mat_data_read;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_din;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_write;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_we0;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_d0;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address1;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce1;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_we0;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_d0;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address1;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce1;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce0;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_we0;
wire   [7:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_d0;
wire   [6:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address1;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce1;
wire   [16:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out_ap_vld;
wire   [16:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out_ap_vld;
wire   [31:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din1;
wire   [47:0] grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din2;
wire    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_ce;
reg    grp_xfUDivResize_fu_186_ap_start_reg;
reg    ap_block_state3_on_subcall_done;
reg    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg;
reg    grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [31:0] read_rows_count_fu_118;
wire   [31:0] read_rows_count_2_fu_692_p3;
wire    ap_CS_fsm_state16;
reg   [31:0] output_rows_count_fu_122;
wire   [31:0] output_rows_count_1_fu_649_p3;
reg   [31:0] first_row_index_1_fu_126;
wire   [31:0] first_row_index_3_fu_710_p3;
reg   [30:0] i_3_fu_130;
wire   [30:0] add_ln404_fu_447_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln404_fu_442_p2;
reg   [16:0] nextYScale_fu_134;
reg   [16:0] indexy_fu_138;
wire   [0:0] icmp_ln376_fu_336_p2;
wire   [0:0] icmp_ln378_fu_346_p2;
wire   [37:0] tmp_2_fu_376_p4;
wire   [31:0] sub_i_fu_390_p2;
wire   [19:0] empty_70_fu_411_p1;
wire   [19:0] empty_71_fu_423_p1;
wire   [31:0] zext_ln404_fu_438_p1;
wire  signed [41:0] trunc_ln409_fu_467_p0;
wire  signed [41:0] conv_i_i25_i515_i_fu_471_p0;
wire  signed [42:0] conv_i_i25_i515_i_fu_471_p1;
wire   [42:0] add_i534_i_fu_475_p2;
wire  signed [41:0] conv_i_i380_i_fu_498_p0;
wire  signed [53:0] conv_i_i380_i_fu_498_p1;
wire   [0:0] tmp_11_fu_532_p3;
wire   [41:0] spec_select110_fu_544_p3;
wire   [41:0] indexy_pre_1_fu_549_p3;
wire   [31:0] zext_ln531_fu_612_p1;
wire   [0:0] icmp_ln531_fu_616_p2;
wire   [0:0] and_ln531_fu_621_p2;
wire   [0:0] icmp_ln532_fu_626_p2;
wire   [0:0] or_ln531_fu_631_p2;
wire   [31:0] add_ln533_fu_637_p2;
wire   [31:0] select_ln531_fu_642_p3;
wire   [31:0] zext_ln536_fu_655_p1;
wire   [0:0] icmp_ln544_fu_664_p2;
wire   [31:0] read_rows_count_1_fu_676_p2;
wire   [0:0] icmp_ln536_fu_659_p2;
wire   [0:0] and_ln536_fu_687_p2;
wire   [31:0] sel_tmp1_fu_681_p3;
wire   [0:0] xor_ln536_fu_699_p2;
wire   [0:0] and_ln536_1_fu_705_p2;
wire   [31:0] first_row_index_2_fu_669_p3;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_xfUDivResize_fu_186_ap_start_reg = 1'b0;
#0 grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg = 1'b0;
#0 grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg = 1'b0;
#0 read_rows_count_fu_118 = 32'd0;
#0 output_rows_count_fu_122 = 32'd0;
#0 first_row_index_1_fu_126 = 32'd0;
#0 i_3_fu_130 = 31'd0;
#0 nextYScale_fu_134 = 17'd0;
#0 indexy_fu_138 = 17'd0;
end

sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_line_buffer_RAM_T2P_BRAM_1bkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_address0),
    .ce0(line_buffer_ce0),
    .we0(line_buffer_we0),
    .d0(line_buffer_d0),
    .q0(line_buffer_q0),
    .address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address1),
    .ce1(line_buffer_ce1),
    .q1(line_buffer_q1)
);

sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_line_buffer_RAM_T2P_BRAM_1bkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buffer_1_address0),
    .ce0(line_buffer_1_ce0),
    .we0(line_buffer_1_we0),
    .d0(line_buffer_1_d0),
    .q0(line_buffer_1_q0),
    .address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address1),
    .ce1(line_buffer_1_ce1),
    .q1(line_buffer_1_q1)
);

sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_line_buffer_RAM_T2P_BRAM_1bkb #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address0),
    .ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce0),
    .we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_we0),
    .d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_d0),
    .q0(line_buffer_2_q0),
    .address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address1),
    .ce1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce1),
    .q1(line_buffer_2_q1)
);

sobel_resize_accel_xfUDivResize grp_xfUDivResize_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfUDivResize_fu_186_ap_start),
    .ap_done(grp_xfUDivResize_fu_186_ap_done),
    .ap_idle(grp_xfUDivResize_fu_186_ap_idle),
    .ap_ready(grp_xfUDivResize_fu_186_ap_ready),
    .in_n(grp_xfUDivResize_fu_186_in_n),
    .in_d(grp_xfUDivResize_fu_186_in_d),
    .ap_return(grp_xfUDivResize_fu_186_ap_return)
);

sobel_resize_accel_scaleCompute_17_42_20_48_16_1_s grp_scaleCompute_17_42_20_48_16_1_s_fu_203(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .currindex(grp_scaleCompute_17_42_20_48_16_1_s_fu_203_currindex),
    .inscale(grp_scaleCompute_17_42_20_48_16_1_s_fu_203_inscale),
    .ap_return(grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return),
    .ap_ce(grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_ce)
);

sobel_resize_accel_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2 grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start),
    .ap_done(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_done),
    .ap_idle(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_idle),
    .ap_ready(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_ready),
    .in_mat_data_dout(in_mat_data_dout),
    .in_mat_data_num_data_valid(3'd0),
    .in_mat_data_fifo_cap(3'd0),
    .in_mat_data_empty_n(in_mat_data_empty_n),
    .in_mat_data_read(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_in_mat_data_read),
    .imgInput_cols_val(imgInput_cols_val),
    .bound(tmp_reg_842),
    .line_buffer_1_address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_address0),
    .line_buffer_1_ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_ce0),
    .line_buffer_1_we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_we0),
    .line_buffer_1_d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_d0),
    .line_buffer_address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_address0),
    .line_buffer_ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_ce0),
    .line_buffer_we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_we0),
    .line_buffer_d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_d0)
);

sobel_resize_accel_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5 grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start),
    .ap_done(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_done),
    .ap_idle(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_idle),
    .ap_ready(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_ready),
    .in_mat_data_dout(in_mat_data_dout),
    .in_mat_data_num_data_valid(3'd0),
    .in_mat_data_fifo_cap(3'd0),
    .in_mat_data_empty_n(in_mat_data_empty_n),
    .in_mat_data_read(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_in_mat_data_read),
    .out_resize_mat_data_din(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_din),
    .out_resize_mat_data_num_data_valid(3'd0),
    .out_resize_mat_data_fifo_cap(3'd0),
    .out_resize_mat_data_full_n(out_resize_mat_data_full_n),
    .out_resize_mat_data_write(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_write),
    .indexy(indexy_fu_138),
    .nextYScale(nextYScale_fu_134),
    .loop_col_count(loop_col_count_reg_872),
    .sub309(sub309_reg_980),
    .sub(sub_reg_967),
    .cmp308(cmp308_reg_974),
    .imgOutput_cols_val(imgOutput_cols_val),
    .slt(slt_reg_923),
    .line_buffer_address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address0),
    .line_buffer_ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce0),
    .line_buffer_we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_we0),
    .line_buffer_d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_d0),
    .line_buffer_q0(line_buffer_q0),
    .line_buffer_address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address1),
    .line_buffer_ce1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce1),
    .line_buffer_q1(line_buffer_q1),
    .line_buffer_1_address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address0),
    .line_buffer_1_ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce0),
    .line_buffer_1_we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_we0),
    .line_buffer_1_d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_d0),
    .line_buffer_1_q0(line_buffer_1_q0),
    .line_buffer_1_address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address1),
    .line_buffer_1_ce1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce1),
    .line_buffer_1_q1(line_buffer_1_q1),
    .sub97(sub97_reg_882),
    .first_row_index_6(first_row_index_1_fu_126),
    .line_buffer_2_address0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address0),
    .line_buffer_2_ce0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce0),
    .line_buffer_2_we0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_we0),
    .line_buffer_2_d0(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_d0),
    .line_buffer_2_q0(line_buffer_2_q0),
    .line_buffer_2_address1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_address1),
    .line_buffer_2_ce1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_2_ce1),
    .line_buffer_2_q1(line_buffer_2_q1),
    .empty_28(trunc_ln320_reg_852),
    .shr_i_i_i_i102_cast(shr_i_i_i_i102_cast_reg_887),
    .empty_29(trunc_ln409_reg_935),
    .add_i_i_i_i_i475_i(add_i_i_i_i_i475_i_reg_986),
    .tmp_cast_30(tmp_cast_reg_940),
    .empty_31(tmp_10_reg_946),
    .indexy_pre_1(empty_72_reg_991),
    .add_i_i_i_i_i349_i(add_i_i_i_i_i349_i_reg_1011),
    .tmp_cast(tmp_cast_73_reg_996),
    .empty_32(tmp_12_reg_1001),
    .empty(empty_74_reg_1006),
    .shl_i_i_i_i_i(shl_i_i_i_i_i_reg_902),
    .indexx_pre_1(indexx_pre_1_reg_907),
    .cmp71(cmp71_reg_959),
    .imgInput_cols_val(imgInput_cols_val),
    .indexy_1_out(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out),
    .indexy_1_out_ap_vld(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out_ap_vld),
    .nextYScale_1_out(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out),
    .nextYScale_1_out_ap_vld(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out_ap_vld),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din1(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din1),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din2(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din2),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_dout0(grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return),
    .grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_ce(grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_ready == 1'b1)) begin
            grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfUDivResize_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3)))) begin
            grp_xfUDivResize_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_xfUDivResize_fu_186_ap_ready == 1'b1)) begin
            grp_xfUDivResize_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        first_row_index_1_fu_126 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        first_row_index_1_fu_126 <= first_row_index_3_fu_710_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_3_fu_130 <= 31'd0;
    end else if (((icmp_ln404_fu_442_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_3_fu_130 <= add_ln404_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indexy_fu_138 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        indexy_fu_138 <= grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nextYScale_fu_134 <= 17'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        nextYScale_fu_134 <= grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        output_rows_count_fu_122 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        output_rows_count_fu_122 <= output_rows_count_1_fu_649_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_rows_count_fu_118 <= 32'd2;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        read_rows_count_fu_118 <= read_rows_count_2_fu_692_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_i_i_i_i_i349_i_reg_1011 <= add_i_i_i_i_i349_i_fu_583_p2;
        add_i_i_i_i_i475_i_reg_986 <= add_i_i_i_i_i475_i_fu_539_p2;
        cmp308_reg_974 <= cmp308_fu_521_p2;
        cmp71_reg_959 <= cmp71_fu_510_p2;
        empty_72_reg_991 <= empty_72_fu_557_p1;
        empty_74_reg_1006 <= empty_74_fu_579_p1;
        sub309_reg_980 <= sub309_fu_526_p2;
        sub_reg_967 <= sub_fu_515_p2;
        tmp_12_reg_1001 <= indexy_pre_1_fu_549_p3[32'd41];
        tmp_cast_73_reg_996 <= {{indexy_pre_1_fu_549_p3[38:22]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        cmp_i_i398_i_reg_951 <= cmp_i_i398_i_fu_502_p2;
        indexy_pre_comp_reg_929 <= grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return;
        tmp_10_reg_946 <= add_i534_i_fu_475_p2[32'd42];
        tmp_cast_reg_940 <= {{add_i534_i_fu_475_p2[38:22]}};
        trunc_ln409_reg_935 <= trunc_ln409_fu_467_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv_i_i12_i530_i1_reg_892[37 : 0] <= conv_i_i12_i530_i1_fu_386_p1[37 : 0];
        indexx_pre_1_reg_907[41 : 22] <= indexx_pre_1_fu_415_p3[41 : 22];
        loop_col_count_reg_872 <= loop_col_count_fu_350_p3;
        loop_row_count_reg_867 <= loop_row_count_fu_340_p3;
        shl_i_i_i373_i_reg_912[41 : 22] <= shl_i_i_i373_i_fu_427_p3[41 : 22];
        shl_i_i_i_i396_i_reg_897[53 : 22] <= shl_i_i_i_i396_i_fu_395_p3[53 : 22];
        shl_i_i_i_i_i_reg_902[53 : 22] <= shl_i_i_i_i_i_fu_403_p3[53 : 22];
        shr_i_i_i_i102_cast_reg_887 <= {{grp_xfUDivResize_fu_186_ap_return[31:10]}};
        sub302_reg_877 <= sub302_fu_356_p2;
        sub97_reg_882 <= sub97_fu_361_p2;
        trunc_ln323_reg_862 <= trunc_ln323_fu_332_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        first_row_index_reg_1025 <= first_row_index_fu_601_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        slt_reg_923 <= slt_fu_462_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_842[32 : 1] <= tmp_fu_304_p3[32 : 1];
        xnew_reg_847[63 : 32] <= xnew_fu_312_p3[63 : 32];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln310_reg_832 <= trunc_ln310_fu_266_p1;
        trunc_ln311_reg_837 <= trunc_ln311_fu_270_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln320_reg_852 <= trunc_ln320_fu_320_p1;
        ynew_reg_857[63 : 32] <= ynew_fu_324_p3[63 : 32];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfUDivResize_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln404_fu_442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln404_fu_442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_ce = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_ce = 1'b1;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_currindex = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_currindex = output_rows_count_fu_122;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_currindex = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_inscale = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_grp_scaleCompute_17_42_20_48_16_1_s_fu_203_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_inscale = trunc_ln323_reg_862;
    end else begin
        grp_scaleCompute_17_42_20_48_16_1_s_fu_203_inscale = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_xfUDivResize_fu_186_in_d = trunc_ln311_reg_837;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_186_in_d = trunc_ln310_reg_832;
    end else begin
        grp_xfUDivResize_fu_186_in_d = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_xfUDivResize_fu_186_in_n = ynew_reg_857;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_xfUDivResize_fu_186_in_n = xnew_reg_847;
    end else begin
        grp_xfUDivResize_fu_186_in_n = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        in_mat_data_read = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_in_mat_data_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_mat_data_read = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_in_mat_data_read;
    end else begin
        in_mat_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_1_address0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_1_address0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_address0;
    end else begin
        line_buffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_1_ce0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_1_ce0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_ce0;
    end else begin
        line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_1_ce1 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_ce1;
    end else begin
        line_buffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_1_d0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_1_d0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_d0;
    end else begin
        line_buffer_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_1_we0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_1_we0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_1_we0;
    end else begin
        line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_address0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_address0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_address0;
    end else begin
        line_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_ce0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_ce0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_ce0;
    end else begin
        line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_ce1 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_ce1;
    end else begin
        line_buffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_d0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_d0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_d0;
    end else begin
        line_buffer_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        line_buffer_we0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_line_buffer_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buffer_we0 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_line_buffer_we0;
    end else begin
        line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        out_resize_mat_data_write = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_write;
    end else begin
        out_resize_mat_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_xfUDivResize_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln404_fu_442_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i534_i_fu_475_p2 = ($signed(conv_i_i12_i530_i1_reg_892) + $signed(conv_i_i25_i515_i_fu_471_p1));

assign add_i_i_i_i_i349_i_fu_583_p2 = (tmp_cast_73_fu_561_p4 + 17'd1);

assign add_i_i_i_i_i475_i_fu_539_p2 = (tmp_cast_reg_940 + 17'd1);

assign add_ln404_fu_447_p2 = (i_3_fu_130 + 31'd1);

assign add_ln533_fu_637_p2 = (output_rows_count_fu_122 + 32'd1);

assign and_ln531_fu_621_p2 = (icmp_ln531_fu_616_p2 & cmp308_reg_974);

assign and_ln536_1_fu_705_p2 = (xor_ln536_fu_699_p2 & cmp71_reg_959);

assign and_ln536_fu_687_p2 = (icmp_ln536_fu_659_p2 & cmp71_reg_959);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_done == 1'b0) | (grp_xfUDivResize_fu_186_ap_done == 1'b0));
end

assign cmp308_fu_521_p2 = ((read_rows_count_fu_118 == imgInput_rows_val) ? 1'b1 : 1'b0);

assign cmp71_fu_510_p2 = ((read_rows_count_fu_118 != imgInput_rows_val) ? 1'b1 : 1'b0);

assign cmp_i_i398_i_fu_502_p2 = (($signed(shl_i_i_i_i396_i_reg_897) < $signed(conv_i_i380_i_fu_498_p1)) ? 1'b1 : 1'b0);

assign conv_i_i12_i530_i1_fu_386_p1 = tmp_2_fu_376_p4;

assign conv_i_i25_i515_i_fu_471_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return;

assign conv_i_i25_i515_i_fu_471_p1 = conv_i_i25_i515_i_fu_471_p0;

assign conv_i_i380_i_fu_498_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return;

assign conv_i_i380_i_fu_498_p1 = conv_i_i380_i_fu_498_p0;

assign empty_70_fu_411_p1 = sub97_fu_361_p2[19:0];

assign empty_71_fu_423_p1 = sub_i_fu_390_p2[19:0];

assign empty_72_fu_557_p1 = indexy_pre_1_fu_549_p3[21:0];

assign empty_74_fu_579_p1 = indexy_pre_1_fu_549_p3[23:0];

assign first_row_index_2_fu_669_p3 = ((icmp_ln544_fu_664_p2[0:0] == 1'b1) ? 32'd0 : first_row_index_reg_1025);

assign first_row_index_3_fu_710_p3 = ((and_ln536_1_fu_705_p2[0:0] == 1'b1) ? first_row_index_2_fu_669_p3 : first_row_index_1_fu_126);

assign first_row_index_fu_601_p2 = (first_row_index_1_fu_126 + 32'd1);

assign grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_354_1_VITIS_LOOP_359_2_fu_218_ap_start_reg;

assign grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_ap_start_reg;

assign grp_xfUDivResize_fu_186_ap_start = grp_xfUDivResize_fu_186_ap_start_reg;

assign icmp_ln376_fu_336_p2 = (($signed(imgOutput_rows_val) > $signed(imgInput_rows_val)) ? 1'b1 : 1'b0);

assign icmp_ln378_fu_346_p2 = (($signed(imgOutput_cols_val) > $signed(imgInput_cols_val)) ? 1'b1 : 1'b0);

assign icmp_ln404_fu_442_p2 = (($signed(zext_ln404_fu_438_p1) < $signed(loop_row_count_reg_867)) ? 1'b1 : 1'b0);

assign icmp_ln531_fu_616_p2 = ((sub_reg_967 == zext_ln531_fu_612_p1) ? 1'b1 : 1'b0);

assign icmp_ln532_fu_626_p2 = ((sub309_reg_980 == zext_ln531_fu_612_p1) ? 1'b1 : 1'b0);

assign icmp_ln536_fu_659_p2 = (($signed(sub_reg_967) > $signed(zext_ln536_fu_655_p1)) ? 1'b1 : 1'b0);

assign icmp_ln544_fu_664_p2 = ((first_row_index_reg_1025 == 32'd3) ? 1'b1 : 1'b0);

assign indexx_pre_1_fu_415_p3 = {{empty_70_fu_411_p1}, {22'd0}};

assign indexy_pre_1_fu_549_p3 = ((tmp_11_fu_532_p3[0:0] == 1'b1) ? 42'd0 : spec_select110_fu_544_p3);

assign loop_col_count_fu_350_p3 = ((icmp_ln378_fu_346_p2[0:0] == 1'b1) ? imgOutput_cols_val : imgInput_cols_val);

assign loop_row_count_fu_340_p3 = ((icmp_ln376_fu_336_p2[0:0] == 1'b1) ? imgOutput_rows_val : imgInput_rows_val);

assign or_ln531_fu_631_p2 = (icmp_ln532_fu_626_p2 | and_ln531_fu_621_p2);

assign out_resize_mat_data_din = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_out_resize_mat_data_din;

assign output_rows_count_1_fu_649_p3 = ((slt_reg_923[0:0] == 1'b1) ? output_rows_count_fu_122 : select_ln531_fu_642_p3);

assign read_rows_count_1_fu_676_p2 = (read_rows_count_fu_118 + 32'd1);

assign read_rows_count_2_fu_692_p3 = ((and_ln536_fu_687_p2[0:0] == 1'b1) ? read_rows_count_fu_118 : sel_tmp1_fu_681_p3);

assign sel_tmp1_fu_681_p3 = ((cmp71_reg_959[0:0] == 1'b1) ? read_rows_count_1_fu_676_p2 : imgInput_rows_val);

assign select_ln531_fu_642_p3 = ((or_ln531_fu_631_p2[0:0] == 1'b1) ? add_ln533_fu_637_p2 : output_rows_count_fu_122);

assign shl_i_i_i373_i_fu_427_p3 = {{empty_71_fu_423_p1}, {22'd0}};

assign shl_i_i_i_i396_i_fu_395_p3 = {{sub_i_fu_390_p2}, {22'd0}};

assign shl_i_i_i_i_i_fu_403_p3 = {{sub97_fu_361_p2}, {22'd0}};

assign slt_fu_462_p2 = (($signed(sub302_reg_877) < $signed(output_rows_count_fu_122)) ? 1'b1 : 1'b0);

assign spec_select110_fu_544_p3 = ((cmp_i_i398_i_reg_951[0:0] == 1'b1) ? shl_i_i_i373_i_reg_912 : indexy_pre_comp_reg_929);

assign sub302_fu_356_p2 = ($signed(imgOutput_rows_val) + $signed(32'd4294967295));

assign sub309_fu_526_p2 = ($signed(read_rows_count_fu_118) + $signed(32'd4294967294));

assign sub97_fu_361_p2 = ($signed(imgInput_cols_val) + $signed(32'd4294967295));

assign sub_fu_515_p2 = ($signed(read_rows_count_fu_118) + $signed(32'd4294967295));

assign sub_i_fu_390_p2 = ($signed(imgInput_rows_val) + $signed(32'd4294967295));

assign tmp_11_fu_532_p3 = indexy_pre_comp_reg_929[32'd41];

assign tmp_2_fu_376_p4 = {{grp_xfUDivResize_fu_186_ap_return[47:10]}};

assign tmp_cast_73_fu_561_p4 = {{indexy_pre_1_fu_549_p3[38:22]}};

assign tmp_fu_304_p3 = {{imgInput_cols_val}, {1'd0}};

assign trunc_ln310_fu_266_p1 = imgOutput_cols_val[15:0];

assign trunc_ln311_fu_270_p1 = imgOutput_rows_val[15:0];

assign trunc_ln320_fu_320_p1 = grp_xfUDivResize_fu_186_ap_return[47:0];

assign trunc_ln323_fu_332_p1 = grp_xfUDivResize_fu_186_ap_return[47:0];

assign trunc_ln409_fu_467_p0 = grp_scaleCompute_17_42_20_48_16_1_s_fu_203_ap_return;

assign trunc_ln409_fu_467_p1 = trunc_ln409_fu_467_p0[21:0];

assign xnew_fu_312_p3 = {{imgInput_cols_val}, {32'd0}};

assign xor_ln536_fu_699_p2 = (icmp_ln536_fu_659_p2 ^ 1'd1);

assign ynew_fu_324_p3 = {{imgInput_rows_val}, {32'd0}};

assign zext_ln404_fu_438_p1 = i_3_fu_130;

assign zext_ln531_fu_612_p1 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_indexy_1_out;

assign zext_ln536_fu_655_p1 = grp_resizeNNBilinear_Pipeline_VITIS_LOOP_411_5_fu_228_nextYScale_1_out;

always @ (posedge ap_clk) begin
    tmp_reg_842[0] <= 1'b0;
    xnew_reg_847[31:0] <= 32'b00000000000000000000000000000000;
    ynew_reg_857[31:0] <= 32'b00000000000000000000000000000000;
    conv_i_i12_i530_i1_reg_892[42:38] <= 5'b00000;
    shl_i_i_i_i396_i_reg_897[21:0] <= 22'b0000000000000000000000;
    shl_i_i_i_i_i_reg_902[21:0] <= 22'b0000000000000000000000;
    indexx_pre_1_reg_907[21:0] <= 22'b0000000000000000000000;
    shl_i_i_i373_i_reg_912[21:0] <= 22'b0000000000000000000000;
end

endmodule //sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s
