-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_resize_accel_resize_1_0_128_128_64_64_1_false_2_2_2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    p_src_rows_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_rows_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_rows_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_rows_empty_n : IN STD_LOGIC;
    p_src_rows_read : OUT STD_LOGIC;
    p_src_cols_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src_cols_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_cols_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    p_src_cols_empty_n : IN STD_LOGIC;
    p_src_cols_read : OUT STD_LOGIC;
    in_mat_data_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_mat_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    in_mat_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    in_mat_data_empty_n : IN STD_LOGIC;
    in_mat_data_read : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_resize_mat_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_resize_mat_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_data_full_n : IN STD_LOGIC;
    out_resize_mat_data_write : OUT STD_LOGIC;
    out_resize_mat_rows_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_resize_mat_rows_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_rows_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_rows_c_full_n : IN STD_LOGIC;
    out_resize_mat_rows_c_write : OUT STD_LOGIC;
    out_resize_mat_cols_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_resize_mat_cols_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_cols_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    out_resize_mat_cols_c_full_n : IN STD_LOGIC;
    out_resize_mat_cols_c_write : OUT STD_LOGIC );
end;


architecture behav of sobel_resize_accel_resize_1_0_128_128_64_64_1_false_2_2_2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal p_src_rows_blk_n : STD_LOGIC;
    signal p_src_cols_blk_n : STD_LOGIC;
    signal out_resize_mat_rows_c_blk_n : STD_LOGIC;
    signal out_resize_mat_cols_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal p_src_cols_read_reg_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_src_rows_read_reg_115 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_idle : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_ready : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_in_mat_data_read : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_write : STD_LOGIC;
    signal grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call12 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgInput_rows_val : IN STD_LOGIC_VECTOR (31 downto 0);
        imgInput_cols_val : IN STD_LOGIC_VECTOR (31 downto 0);
        in_mat_data_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        in_mat_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        in_mat_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        in_mat_data_empty_n : IN STD_LOGIC;
        in_mat_data_read : OUT STD_LOGIC;
        imgOutput_rows_val : IN STD_LOGIC_VECTOR (31 downto 0);
        imgOutput_cols_val : IN STD_LOGIC_VECTOR (31 downto 0);
        out_resize_mat_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_resize_mat_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        out_resize_mat_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        out_resize_mat_data_full_n : IN STD_LOGIC;
        out_resize_mat_data_write : OUT STD_LOGIC );
    end component;



begin
    grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84 : component sobel_resize_accel_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start,
        ap_done => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done,
        ap_idle => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_idle,
        ap_ready => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_ready,
        imgInput_rows_val => p_src_rows_read_reg_115,
        imgInput_cols_val => p_src_cols_read_reg_110,
        in_mat_data_dout => in_mat_data_dout,
        in_mat_data_num_data_valid => ap_const_lv3_0,
        in_mat_data_fifo_cap => ap_const_lv3_0,
        in_mat_data_empty_n => in_mat_data_empty_n,
        in_mat_data_read => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_in_mat_data_read,
        imgOutput_rows_val => p_read,
        imgOutput_cols_val => p_read1,
        out_resize_mat_data_din => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_din,
        out_resize_mat_data_num_data_valid => ap_const_lv3_0,
        out_resize_mat_data_fifo_cap => ap_const_lv3_0,
        out_resize_mat_data_full_n => out_resize_mat_data_full_n,
        out_resize_mat_data_write => grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_write);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call12) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                p_src_cols_read_reg_110 <= p_src_cols_dout;
                p_src_rows_read_reg_115 <= p_src_rows_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done)
    begin
        if ((grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, p_src_rows_empty_n, p_src_cols_empty_n, out_resize_mat_rows_c_full_n, out_resize_mat_cols_c_full_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (out_resize_mat_cols_c_full_n = ap_const_logic_0) or (out_resize_mat_rows_c_full_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call12_assign_proc : process(real_start, ap_done_reg, p_src_rows_empty_n, p_src_cols_empty_n, out_resize_mat_rows_c_full_n, out_resize_mat_cols_c_full_n)
    begin
                ap_block_state1_ignore_call12 <= ((real_start = ap_const_logic_0) or (out_resize_mat_cols_c_full_n = ap_const_logic_0) or (out_resize_mat_rows_c_full_n = ap_const_logic_0) or (p_src_cols_empty_n = ap_const_logic_0) or (p_src_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start <= grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_start_reg;

    in_mat_data_read_assign_proc : process(grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_in_mat_data_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            in_mat_data_read <= grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_in_mat_data_read;
        else 
            in_mat_data_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    out_resize_mat_cols_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, out_resize_mat_cols_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_resize_mat_cols_c_blk_n <= out_resize_mat_cols_c_full_n;
        else 
            out_resize_mat_cols_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_resize_mat_cols_c_din <= p_read1;

    out_resize_mat_cols_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_resize_mat_cols_c_write <= ap_const_logic_1;
        else 
            out_resize_mat_cols_c_write <= ap_const_logic_0;
        end if; 
    end process;

    out_resize_mat_data_din <= grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_din;

    out_resize_mat_data_write_assign_proc : process(grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            out_resize_mat_data_write <= grp_resizeNNBilinear_0_128_128_1_false_2_2_64_64_1_2_s_fu_84_out_resize_mat_data_write;
        else 
            out_resize_mat_data_write <= ap_const_logic_0;
        end if; 
    end process;


    out_resize_mat_rows_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, out_resize_mat_rows_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_resize_mat_rows_c_blk_n <= out_resize_mat_rows_c_full_n;
        else 
            out_resize_mat_rows_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_resize_mat_rows_c_din <= p_read;

    out_resize_mat_rows_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            out_resize_mat_rows_c_write <= ap_const_logic_1;
        else 
            out_resize_mat_rows_c_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_cols_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_blk_n <= p_src_cols_empty_n;
        else 
            p_src_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_cols_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_cols_read <= ap_const_logic_1;
        else 
            p_src_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    p_src_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, p_src_rows_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_blk_n <= p_src_rows_empty_n;
        else 
            p_src_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_rows_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src_rows_read <= ap_const_logic_1;
        else 
            p_src_rows_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
