# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sxy/Desktop/vivado_workspace/lab1_sobel/Lab1_sobel _max/Lab1_sobel.srcs/sources_1/bd/sobel/ip/sobel_xbar_3/sobel_xbar_3.xci
# IP: The module: 'sobel_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sxy/Desktop/vivado_workspace/lab1_sobel/Lab1_sobel _max/Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_xbar_3/sobel_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sobel_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/sxy/Desktop/vivado_workspace/lab1_sobel/Lab1_sobel _max/Lab1_sobel.srcs/sources_1/bd/sobel/ip/sobel_xbar_3/sobel_xbar_3.xci
# IP: The module: 'sobel_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sxy/Desktop/vivado_workspace/lab1_sobel/Lab1_sobel _max/Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_xbar_3/sobel_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sobel_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
