// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_resize_accel_sobel_resize_accel,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.543875,HLS_SYN_LAT=8213,HLS_SYN_TPT=8213,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=13544,HLS_SYN_LUT=16501,HLS_VERSION=2023_2}" *)

module sobel_resize_accel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM3_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM3_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_USER_VALUE = 0;
parameter    C_M_AXI_GMEM3_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM3_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM3_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_AWADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_AWID;
output  [7:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [C_M_AXI_GMEM3_AWUSER_WIDTH - 1:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_WDATA;
output  [C_M_AXI_GMEM3_WSTRB_WIDTH - 1:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_WID;
output  [C_M_AXI_GMEM3_WUSER_WIDTH - 1:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_ARADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_ARID;
output  [7:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [C_M_AXI_GMEM3_ARUSER_WIDTH - 1:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_RID;
input  [C_M_AXI_GMEM3_RUSER_WIDTH - 1:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_BID;
input  [C_M_AXI_GMEM3_BUSER_WIDTH - 1:0] m_axi_gmem3_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] img_inp;
wire   [63:0] img_out1;
wire   [63:0] img_out2;
wire   [31:0] rows_in;
wire   [31:0] cols_in;
wire   [31:0] rows_out;
wire   [31:0] cols_out;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [7:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [10:0] gmem1_RFIFONUM;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [7:0] gmem2_RDATA;
wire   [10:0] gmem2_RFIFONUM;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    gmem3_AWREADY;
wire    gmem3_WREADY;
wire    gmem3_ARREADY;
wire    gmem3_RVALID;
wire   [7:0] gmem3_RDATA;
wire   [10:0] gmem3_RFIFONUM;
wire    gmem3_BVALID;
wire   [1:0] gmem3_BRESP;
wire   [0:0] gmem3_BID;
wire   [0:0] gmem3_BUSER;
wire    entry_proc13_U0_ap_start;
wire    entry_proc13_U0_ap_done;
wire    entry_proc13_U0_ap_continue;
wire    entry_proc13_U0_ap_idle;
wire    entry_proc13_U0_ap_ready;
wire   [63:0] entry_proc13_U0_img_out1_c_din;
wire    entry_proc13_U0_img_out1_c_write;
wire   [63:0] entry_proc13_U0_img_out2_c_din;
wire    entry_proc13_U0_img_out2_c_write;
wire    Block_entry1_proc_U0_ap_start;
wire    Block_entry1_proc_U0_ap_done;
wire    Block_entry1_proc_U0_ap_continue;
wire    Block_entry1_proc_U0_ap_idle;
wire    Block_entry1_proc_U0_ap_ready;
wire   [31:0] Block_entry1_proc_U0_ap_return_0;
wire   [31:0] Block_entry1_proc_U0_ap_return_1;
wire   [31:0] Block_entry1_proc_U0_ap_return_2;
wire   [31:0] Block_entry1_proc_U0_ap_return_3;
wire    ap_channel_done_out_resize_mat_cols_c18_channel;
wire    out_resize_mat_cols_c18_channel_full_n;
reg    ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel;
wire    ap_sync_channel_write_out_resize_mat_cols_c18_channel;
wire    ap_channel_done_out_resize_mat_rows_c17_channel;
wire    out_resize_mat_rows_c17_channel_full_n;
reg    ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel;
wire    ap_sync_channel_write_out_resize_mat_rows_c17_channel;
wire    ap_channel_done_in_mat_cols_c16_channel;
wire    in_mat_cols_c16_channel_full_n;
reg    ap_sync_reg_channel_write_in_mat_cols_c16_channel;
wire    ap_sync_channel_write_in_mat_cols_c16_channel;
wire    ap_channel_done_in_mat_rows_c15_channel;
wire    in_mat_rows_c15_channel_full_n;
reg    ap_sync_reg_channel_write_in_mat_rows_c15_channel;
wire    ap_sync_channel_write_in_mat_rows_c15_channel;
wire    Array2xfMat_8_0_128_128_1_2_U0_ap_start;
wire    Array2xfMat_8_0_128_128_1_2_U0_ap_done;
wire    Array2xfMat_8_0_128_128_1_2_U0_ap_continue;
wire    Array2xfMat_8_0_128_128_1_2_U0_ap_idle;
wire    Array2xfMat_8_0_128_128_1_2_U0_ap_ready;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWVALID;
wire   [63:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWADDR;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWID;
wire   [31:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWLEN;
wire   [2:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWBURST;
wire   [1:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWPROT;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWQOS;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWREGION;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWUSER;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WVALID;
wire   [7:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WDATA;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WSTRB;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WLAST;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WID;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WUSER;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARVALID;
wire   [63:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARADDR;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARID;
wire   [31:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARLEN;
wire   [2:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARBURST;
wire   [1:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARPROT;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARQOS;
wire   [3:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARREGION;
wire   [0:0] Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARUSER;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_RREADY;
wire    Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_BREADY;
wire   [7:0] Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_din;
wire    Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_write;
wire   [31:0] Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_din;
wire    Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_write;
wire   [31:0] Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_din;
wire    Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_write;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_start;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_done;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_continue;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_idle;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_ready;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_start_out;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_start_write;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_rows_read;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_cols_read;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_in_mat_data_read;
wire   [7:0] resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_din;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_write;
wire   [31:0] resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_din;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_write;
wire   [31:0] resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_din;
wire    resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_write;
wire    Block_entry14_proc_U0_ap_start;
wire    Block_entry14_proc_U0_ap_done;
wire    Block_entry14_proc_U0_ap_continue;
wire    Block_entry14_proc_U0_ap_idle;
wire    Block_entry14_proc_U0_ap_ready;
wire   [31:0] Block_entry14_proc_U0_ap_return_0;
wire   [31:0] Block_entry14_proc_U0_ap_return_1;
wire   [31:0] Block_entry14_proc_U0_ap_return_2;
wire   [31:0] Block_entry14_proc_U0_ap_return_3;
wire    ap_channel_done_p_dstgy_cols_channel;
wire    p_dstgy_cols_channel_full_n;
reg    ap_sync_reg_channel_write_p_dstgy_cols_channel;
wire    ap_sync_channel_write_p_dstgy_cols_channel;
wire    ap_channel_done_p_dstgy_rows_channel;
wire    p_dstgy_rows_channel_full_n;
reg    ap_sync_reg_channel_write_p_dstgy_rows_channel;
wire    ap_sync_channel_write_p_dstgy_rows_channel;
wire    ap_channel_done_p_dstgx_cols_channel;
wire    p_dstgx_cols_channel_full_n;
reg    ap_sync_reg_channel_write_p_dstgx_cols_channel;
wire    ap_sync_channel_write_p_dstgx_cols_channel;
wire    ap_channel_done_p_dstgx_rows_channel;
wire    p_dstgx_rows_channel_full_n;
reg    ap_sync_reg_channel_write_p_dstgx_rows_channel;
wire    ap_sync_channel_write_p_dstgx_rows_channel;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_start;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_done;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_continue;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_idle;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_ready;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_rows_read;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_cols_read;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_out_resize_mat_data_read;
wire   [7:0] Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_din;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_write;
wire   [7:0] Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_din;
wire    Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_write;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_ap_start;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_ap_done;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_ap_continue;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_ap_idle;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_ap_ready;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_p_dstgx_data_read;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWVALID;
wire   [63:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWADDR;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWID;
wire   [31:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWLEN;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWBURST;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWPROT;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWQOS;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWREGION;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WVALID;
wire   [7:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WDATA;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WSTRB;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WLAST;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WID;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARVALID;
wire   [63:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARADDR;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARID;
wire   [31:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARLEN;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARBURST;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARPROT;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARQOS;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARREGION;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_RREADY;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_BREADY;
wire    xfMat2Array_8_0_64_64_1_2_1_U0_dstPtr_read;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_start;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_done;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_continue;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_idle;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_ready;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_p_dstgy_data_read;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWVALID;
wire   [63:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWADDR;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWID;
wire   [31:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWLEN;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWSIZE;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWBURST;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWLOCK;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWCACHE;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWPROT;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWQOS;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWREGION;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WVALID;
wire   [7:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WDATA;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WSTRB;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WLAST;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WID;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARVALID;
wire   [63:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARADDR;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARID;
wire   [31:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARLEN;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARSIZE;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARBURST;
wire   [1:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARLOCK;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARCACHE;
wire   [2:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARPROT;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARQOS;
wire   [3:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARREGION;
wire   [0:0] xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARUSER;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_RREADY;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_BREADY;
wire    xfMat2Array_8_0_64_64_1_2_1_1_U0_dstPtr_read;
wire    img_out1_c_full_n;
wire   [63:0] img_out1_c_dout;
wire   [3:0] img_out1_c_num_data_valid;
wire   [3:0] img_out1_c_fifo_cap;
wire    img_out1_c_empty_n;
wire    img_out2_c_full_n;
wire   [63:0] img_out2_c_dout;
wire   [3:0] img_out2_c_num_data_valid;
wire   [3:0] img_out2_c_fifo_cap;
wire    img_out2_c_empty_n;
wire   [31:0] in_mat_rows_c15_channel_dout;
wire   [2:0] in_mat_rows_c15_channel_num_data_valid;
wire   [2:0] in_mat_rows_c15_channel_fifo_cap;
wire    in_mat_rows_c15_channel_empty_n;
wire   [31:0] in_mat_cols_c16_channel_dout;
wire   [2:0] in_mat_cols_c16_channel_num_data_valid;
wire   [2:0] in_mat_cols_c16_channel_fifo_cap;
wire    in_mat_cols_c16_channel_empty_n;
wire   [31:0] out_resize_mat_rows_c17_channel_dout;
wire   [2:0] out_resize_mat_rows_c17_channel_num_data_valid;
wire   [2:0] out_resize_mat_rows_c17_channel_fifo_cap;
wire    out_resize_mat_rows_c17_channel_empty_n;
wire   [31:0] out_resize_mat_cols_c18_channel_dout;
wire   [2:0] out_resize_mat_cols_c18_channel_num_data_valid;
wire   [2:0] out_resize_mat_cols_c18_channel_fifo_cap;
wire    out_resize_mat_cols_c18_channel_empty_n;
wire    in_mat_data_full_n;
wire   [7:0] in_mat_data_dout;
wire   [2:0] in_mat_data_num_data_valid;
wire   [2:0] in_mat_data_fifo_cap;
wire    in_mat_data_empty_n;
wire    in_mat_rows_c_full_n;
wire   [31:0] in_mat_rows_c_dout;
wire   [2:0] in_mat_rows_c_num_data_valid;
wire   [2:0] in_mat_rows_c_fifo_cap;
wire    in_mat_rows_c_empty_n;
wire    in_mat_cols_c_full_n;
wire   [31:0] in_mat_cols_c_dout;
wire   [2:0] in_mat_cols_c_num_data_valid;
wire   [2:0] in_mat_cols_c_fifo_cap;
wire    in_mat_cols_c_empty_n;
wire    out_resize_mat_data_full_n;
wire   [7:0] out_resize_mat_data_dout;
wire   [2:0] out_resize_mat_data_num_data_valid;
wire   [2:0] out_resize_mat_data_fifo_cap;
wire    out_resize_mat_data_empty_n;
wire    out_resize_mat_rows_c_full_n;
wire   [31:0] out_resize_mat_rows_c_dout;
wire   [2:0] out_resize_mat_rows_c_num_data_valid;
wire   [2:0] out_resize_mat_rows_c_fifo_cap;
wire    out_resize_mat_rows_c_empty_n;
wire    out_resize_mat_cols_c_full_n;
wire   [31:0] out_resize_mat_cols_c_dout;
wire   [2:0] out_resize_mat_cols_c_num_data_valid;
wire   [2:0] out_resize_mat_cols_c_fifo_cap;
wire    out_resize_mat_cols_c_empty_n;
wire   [31:0] p_dstgx_rows_channel_dout;
wire   [3:0] p_dstgx_rows_channel_num_data_valid;
wire   [3:0] p_dstgx_rows_channel_fifo_cap;
wire    p_dstgx_rows_channel_empty_n;
wire   [31:0] p_dstgx_cols_channel_dout;
wire   [3:0] p_dstgx_cols_channel_num_data_valid;
wire   [3:0] p_dstgx_cols_channel_fifo_cap;
wire    p_dstgx_cols_channel_empty_n;
wire   [31:0] p_dstgy_rows_channel_dout;
wire   [3:0] p_dstgy_rows_channel_num_data_valid;
wire   [3:0] p_dstgy_rows_channel_fifo_cap;
wire    p_dstgy_rows_channel_empty_n;
wire   [31:0] p_dstgy_cols_channel_dout;
wire   [3:0] p_dstgy_cols_channel_num_data_valid;
wire   [3:0] p_dstgy_cols_channel_fifo_cap;
wire    p_dstgy_cols_channel_empty_n;
wire    p_dstgx_data_full_n;
wire   [7:0] p_dstgx_data_dout;
wire   [2:0] p_dstgx_data_num_data_valid;
wire   [2:0] p_dstgx_data_fifo_cap;
wire    p_dstgx_data_empty_n;
wire    p_dstgy_data_full_n;
wire   [7:0] p_dstgy_data_dout;
wire   [2:0] p_dstgy_data_num_data_valid;
wire   [2:0] p_dstgy_data_fifo_cap;
wire    p_dstgy_data_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc13_U0_ap_ready;
wire    ap_sync_entry_proc13_U0_ap_ready;
reg    ap_sync_reg_Block_entry1_proc_U0_ap_ready;
wire    ap_sync_Block_entry1_proc_U0_ap_ready;
reg    ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready;
wire    ap_sync_Array2xfMat_8_0_128_128_1_2_U0_ap_ready;
reg    ap_sync_reg_Block_entry14_proc_U0_ap_ready;
wire    ap_sync_Block_entry14_proc_U0_ap_ready;
wire   [0:0] start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_din;
wire    start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_full_n;
wire   [0:0] start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_dout;
wire    start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel = 1'b0;
#0 ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel = 1'b0;
#0 ap_sync_reg_channel_write_in_mat_cols_c16_channel = 1'b0;
#0 ap_sync_reg_channel_write_in_mat_rows_c15_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_dstgy_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_dstgy_rows_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_dstgx_cols_channel = 1'b0;
#0 ap_sync_reg_channel_write_p_dstgx_rows_channel = 1'b0;
#0 ap_sync_reg_entry_proc13_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_entry1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Block_entry14_proc_U0_ap_ready = 1'b0;
end

sobel_resize_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img_inp(img_inp),
    .img_out1(img_out1),
    .img_out2(img_out2),
    .rows_in(rows_in),
    .cols_in(cols_in),
    .rows_out(rows_out),
    .cols_out(cols_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sobel_resize_accel_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARADDR),
    .I_ARLEN(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

sobel_resize_accel_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RFIFONUM(gmem2_RFIFONUM),
    .I_AWVALID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWADDR),
    .I_AWLEN(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWLEN),
    .I_WVALID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WDATA),
    .I_WSTRB(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WSTRB),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_BREADY)
);

sobel_resize_accel_gmem3_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM3_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem3_m_axi_U(
    .AWVALID(m_axi_gmem3_AWVALID),
    .AWREADY(m_axi_gmem3_AWREADY),
    .AWADDR(m_axi_gmem3_AWADDR),
    .AWID(m_axi_gmem3_AWID),
    .AWLEN(m_axi_gmem3_AWLEN),
    .AWSIZE(m_axi_gmem3_AWSIZE),
    .AWBURST(m_axi_gmem3_AWBURST),
    .AWLOCK(m_axi_gmem3_AWLOCK),
    .AWCACHE(m_axi_gmem3_AWCACHE),
    .AWPROT(m_axi_gmem3_AWPROT),
    .AWQOS(m_axi_gmem3_AWQOS),
    .AWREGION(m_axi_gmem3_AWREGION),
    .AWUSER(m_axi_gmem3_AWUSER),
    .WVALID(m_axi_gmem3_WVALID),
    .WREADY(m_axi_gmem3_WREADY),
    .WDATA(m_axi_gmem3_WDATA),
    .WSTRB(m_axi_gmem3_WSTRB),
    .WLAST(m_axi_gmem3_WLAST),
    .WID(m_axi_gmem3_WID),
    .WUSER(m_axi_gmem3_WUSER),
    .ARVALID(m_axi_gmem3_ARVALID),
    .ARREADY(m_axi_gmem3_ARREADY),
    .ARADDR(m_axi_gmem3_ARADDR),
    .ARID(m_axi_gmem3_ARID),
    .ARLEN(m_axi_gmem3_ARLEN),
    .ARSIZE(m_axi_gmem3_ARSIZE),
    .ARBURST(m_axi_gmem3_ARBURST),
    .ARLOCK(m_axi_gmem3_ARLOCK),
    .ARCACHE(m_axi_gmem3_ARCACHE),
    .ARPROT(m_axi_gmem3_ARPROT),
    .ARQOS(m_axi_gmem3_ARQOS),
    .ARREGION(m_axi_gmem3_ARREGION),
    .ARUSER(m_axi_gmem3_ARUSER),
    .RVALID(m_axi_gmem3_RVALID),
    .RREADY(m_axi_gmem3_RREADY),
    .RDATA(m_axi_gmem3_RDATA),
    .RLAST(m_axi_gmem3_RLAST),
    .RID(m_axi_gmem3_RID),
    .RUSER(m_axi_gmem3_RUSER),
    .RRESP(m_axi_gmem3_RRESP),
    .BVALID(m_axi_gmem3_BVALID),
    .BREADY(m_axi_gmem3_BREADY),
    .BRESP(m_axi_gmem3_BRESP),
    .BID(m_axi_gmem3_BID),
    .BUSER(m_axi_gmem3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem3_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(gmem3_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem3_RDATA),
    .I_RFIFONUM(gmem3_RFIFONUM),
    .I_AWVALID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWVALID),
    .I_AWREADY(gmem3_AWREADY),
    .I_AWADDR(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWADDR),
    .I_AWLEN(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWLEN),
    .I_WVALID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WVALID),
    .I_WREADY(gmem3_WREADY),
    .I_WDATA(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WDATA),
    .I_WSTRB(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WSTRB),
    .I_BVALID(gmem3_BVALID),
    .I_BREADY(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_BREADY)
);

sobel_resize_accel_entry_proc13 entry_proc13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc13_U0_ap_start),
    .ap_done(entry_proc13_U0_ap_done),
    .ap_continue(entry_proc13_U0_ap_continue),
    .ap_idle(entry_proc13_U0_ap_idle),
    .ap_ready(entry_proc13_U0_ap_ready),
    .img_out1(img_out1),
    .img_out1_c_din(entry_proc13_U0_img_out1_c_din),
    .img_out1_c_num_data_valid(img_out1_c_num_data_valid),
    .img_out1_c_fifo_cap(img_out1_c_fifo_cap),
    .img_out1_c_full_n(img_out1_c_full_n),
    .img_out1_c_write(entry_proc13_U0_img_out1_c_write),
    .img_out2(img_out2),
    .img_out2_c_din(entry_proc13_U0_img_out2_c_din),
    .img_out2_c_num_data_valid(img_out2_c_num_data_valid),
    .img_out2_c_fifo_cap(img_out2_c_fifo_cap),
    .img_out2_c_full_n(img_out2_c_full_n),
    .img_out2_c_write(entry_proc13_U0_img_out2_c_write)
);

sobel_resize_accel_Block_entry1_proc Block_entry1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry1_proc_U0_ap_start),
    .ap_done(Block_entry1_proc_U0_ap_done),
    .ap_continue(Block_entry1_proc_U0_ap_continue),
    .ap_idle(Block_entry1_proc_U0_ap_idle),
    .ap_ready(Block_entry1_proc_U0_ap_ready),
    .rows_in(rows_in),
    .cols_in(cols_in),
    .rows_out(rows_out),
    .cols_out(cols_out),
    .ap_return_0(Block_entry1_proc_U0_ap_return_0),
    .ap_return_1(Block_entry1_proc_U0_ap_return_1),
    .ap_return_2(Block_entry1_proc_U0_ap_return_2),
    .ap_return_3(Block_entry1_proc_U0_ap_return_3)
);

sobel_resize_accel_Array2xfMat_8_0_128_128_1_2_s Array2xfMat_8_0_128_128_1_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Array2xfMat_8_0_128_128_1_2_U0_ap_start),
    .ap_done(Array2xfMat_8_0_128_128_1_2_U0_ap_done),
    .ap_continue(Array2xfMat_8_0_128_128_1_2_U0_ap_continue),
    .ap_idle(Array2xfMat_8_0_128_128_1_2_U0_ap_idle),
    .ap_ready(Array2xfMat_8_0_128_128_1_2_U0_ap_ready),
    .m_axi_gmem1_AWVALID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(Array2xfMat_8_0_128_128_1_2_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .srcPtr(img_inp),
    .p_read(in_mat_rows_c15_channel_dout),
    .p_read1(in_mat_cols_c16_channel_dout),
    .in_mat_data_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_din),
    .in_mat_data_num_data_valid(in_mat_data_num_data_valid),
    .in_mat_data_fifo_cap(in_mat_data_fifo_cap),
    .in_mat_data_full_n(in_mat_data_full_n),
    .in_mat_data_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_write),
    .in_mat_rows_c_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_din),
    .in_mat_rows_c_num_data_valid(in_mat_rows_c_num_data_valid),
    .in_mat_rows_c_fifo_cap(in_mat_rows_c_fifo_cap),
    .in_mat_rows_c_full_n(in_mat_rows_c_full_n),
    .in_mat_rows_c_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_write),
    .in_mat_cols_c_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_din),
    .in_mat_cols_c_num_data_valid(in_mat_cols_c_num_data_valid),
    .in_mat_cols_c_fifo_cap(in_mat_cols_c_fifo_cap),
    .in_mat_cols_c_full_n(in_mat_cols_c_full_n),
    .in_mat_cols_c_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_write)
);

sobel_resize_accel_resize_1_0_128_128_64_64_1_false_2_2_2_s resize_1_0_128_128_64_64_1_false_2_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_start),
    .start_full_n(start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_full_n),
    .ap_done(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_done),
    .ap_continue(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_continue),
    .ap_idle(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_idle),
    .ap_ready(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_ready),
    .start_out(resize_1_0_128_128_64_64_1_false_2_2_2_U0_start_out),
    .start_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_start_write),
    .p_src_rows_dout(in_mat_rows_c_dout),
    .p_src_rows_num_data_valid(in_mat_rows_c_num_data_valid),
    .p_src_rows_fifo_cap(in_mat_rows_c_fifo_cap),
    .p_src_rows_empty_n(in_mat_rows_c_empty_n),
    .p_src_rows_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_rows_read),
    .p_src_cols_dout(in_mat_cols_c_dout),
    .p_src_cols_num_data_valid(in_mat_cols_c_num_data_valid),
    .p_src_cols_fifo_cap(in_mat_cols_c_fifo_cap),
    .p_src_cols_empty_n(in_mat_cols_c_empty_n),
    .p_src_cols_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_cols_read),
    .in_mat_data_dout(in_mat_data_dout),
    .in_mat_data_num_data_valid(in_mat_data_num_data_valid),
    .in_mat_data_fifo_cap(in_mat_data_fifo_cap),
    .in_mat_data_empty_n(in_mat_data_empty_n),
    .in_mat_data_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_in_mat_data_read),
    .p_read(out_resize_mat_rows_c17_channel_dout),
    .p_read1(out_resize_mat_cols_c18_channel_dout),
    .out_resize_mat_data_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_din),
    .out_resize_mat_data_num_data_valid(out_resize_mat_data_num_data_valid),
    .out_resize_mat_data_fifo_cap(out_resize_mat_data_fifo_cap),
    .out_resize_mat_data_full_n(out_resize_mat_data_full_n),
    .out_resize_mat_data_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_write),
    .out_resize_mat_rows_c_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_din),
    .out_resize_mat_rows_c_num_data_valid(out_resize_mat_rows_c_num_data_valid),
    .out_resize_mat_rows_c_fifo_cap(out_resize_mat_rows_c_fifo_cap),
    .out_resize_mat_rows_c_full_n(out_resize_mat_rows_c_full_n),
    .out_resize_mat_rows_c_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_write),
    .out_resize_mat_cols_c_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_din),
    .out_resize_mat_cols_c_num_data_valid(out_resize_mat_cols_c_num_data_valid),
    .out_resize_mat_cols_c_fifo_cap(out_resize_mat_cols_c_fifo_cap),
    .out_resize_mat_cols_c_full_n(out_resize_mat_cols_c_full_n),
    .out_resize_mat_cols_c_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_write)
);

sobel_resize_accel_Block_entry14_proc Block_entry14_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_entry14_proc_U0_ap_start),
    .ap_done(Block_entry14_proc_U0_ap_done),
    .ap_continue(Block_entry14_proc_U0_ap_continue),
    .ap_idle(Block_entry14_proc_U0_ap_idle),
    .ap_ready(Block_entry14_proc_U0_ap_ready),
    .rows_out(rows_out),
    .cols_out(cols_out),
    .ap_return_0(Block_entry14_proc_U0_ap_return_0),
    .ap_return_1(Block_entry14_proc_U0_ap_return_1),
    .ap_return_2(Block_entry14_proc_U0_ap_return_2),
    .ap_return_3(Block_entry14_proc_U0_ap_return_3)
);

sobel_resize_accel_Sobel_0_3_0_0_64_64_1_false_2_2_2_s Sobel_0_3_0_0_64_64_1_false_2_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_start),
    .ap_done(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_done),
    .ap_continue(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_continue),
    .ap_idle(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_idle),
    .ap_ready(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_ready),
    .p_src_mat_rows_dout(out_resize_mat_rows_c_dout),
    .p_src_mat_rows_num_data_valid(out_resize_mat_rows_c_num_data_valid),
    .p_src_mat_rows_fifo_cap(out_resize_mat_rows_c_fifo_cap),
    .p_src_mat_rows_empty_n(out_resize_mat_rows_c_empty_n),
    .p_src_mat_rows_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_rows_read),
    .p_src_mat_cols_dout(out_resize_mat_cols_c_dout),
    .p_src_mat_cols_num_data_valid(out_resize_mat_cols_c_num_data_valid),
    .p_src_mat_cols_fifo_cap(out_resize_mat_cols_c_fifo_cap),
    .p_src_mat_cols_empty_n(out_resize_mat_cols_c_empty_n),
    .p_src_mat_cols_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_cols_read),
    .out_resize_mat_data_dout(out_resize_mat_data_dout),
    .out_resize_mat_data_num_data_valid(out_resize_mat_data_num_data_valid),
    .out_resize_mat_data_fifo_cap(out_resize_mat_data_fifo_cap),
    .out_resize_mat_data_empty_n(out_resize_mat_data_empty_n),
    .out_resize_mat_data_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_out_resize_mat_data_read),
    .p_dstgx_data_din(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_din),
    .p_dstgx_data_num_data_valid(p_dstgx_data_num_data_valid),
    .p_dstgx_data_fifo_cap(p_dstgx_data_fifo_cap),
    .p_dstgx_data_full_n(p_dstgx_data_full_n),
    .p_dstgx_data_write(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_write),
    .p_dstgy_data_din(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_din),
    .p_dstgy_data_num_data_valid(p_dstgy_data_num_data_valid),
    .p_dstgy_data_fifo_cap(p_dstgy_data_fifo_cap),
    .p_dstgy_data_full_n(p_dstgy_data_full_n),
    .p_dstgy_data_write(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_write)
);

sobel_resize_accel_xfMat2Array_8_0_64_64_1_2_1_s xfMat2Array_8_0_64_64_1_2_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2Array_8_0_64_64_1_2_1_U0_ap_start),
    .ap_done(xfMat2Array_8_0_64_64_1_2_1_U0_ap_done),
    .ap_continue(xfMat2Array_8_0_64_64_1_2_1_U0_ap_continue),
    .ap_idle(xfMat2Array_8_0_64_64_1_2_1_U0_ap_idle),
    .ap_ready(xfMat2Array_8_0_64_64_1_2_1_U0_ap_ready),
    .p_read(p_dstgx_rows_channel_dout),
    .p_read1(p_dstgx_cols_channel_dout),
    .p_dstgx_data_dout(p_dstgx_data_dout),
    .p_dstgx_data_num_data_valid(p_dstgx_data_num_data_valid),
    .p_dstgx_data_fifo_cap(p_dstgx_data_fifo_cap),
    .p_dstgx_data_empty_n(p_dstgx_data_empty_n),
    .p_dstgx_data_read(xfMat2Array_8_0_64_64_1_2_1_U0_p_dstgx_data_read),
    .m_axi_gmem2_AWVALID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(gmem2_WREADY),
    .m_axi_gmem2_WDATA(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(8'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(11'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(gmem2_BVALID),
    .m_axi_gmem2_BREADY(xfMat2Array_8_0_64_64_1_2_1_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(gmem2_BRESP),
    .m_axi_gmem2_BID(gmem2_BID),
    .m_axi_gmem2_BUSER(gmem2_BUSER),
    .dstPtr_dout(img_out1_c_dout),
    .dstPtr_num_data_valid(img_out1_c_num_data_valid),
    .dstPtr_fifo_cap(img_out1_c_fifo_cap),
    .dstPtr_empty_n(img_out1_c_empty_n),
    .dstPtr_read(xfMat2Array_8_0_64_64_1_2_1_U0_dstPtr_read)
);

sobel_resize_accel_xfMat2Array_8_0_64_64_1_2_1_1 xfMat2Array_8_0_64_64_1_2_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_start),
    .ap_done(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_done),
    .ap_continue(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_continue),
    .ap_idle(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_idle),
    .ap_ready(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_ready),
    .p_read(p_dstgy_rows_channel_dout),
    .p_read1(p_dstgy_cols_channel_dout),
    .p_dstgy_data_dout(p_dstgy_data_dout),
    .p_dstgy_data_num_data_valid(p_dstgy_data_num_data_valid),
    .p_dstgy_data_fifo_cap(p_dstgy_data_fifo_cap),
    .p_dstgy_data_empty_n(p_dstgy_data_empty_n),
    .p_dstgy_data_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_p_dstgy_data_read),
    .m_axi_gmem3_AWVALID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(gmem3_AWREADY),
    .m_axi_gmem3_AWADDR(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(gmem3_WREADY),
    .m_axi_gmem3_WDATA(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(1'b0),
    .m_axi_gmem3_ARADDR(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(1'b0),
    .m_axi_gmem3_RREADY(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(8'd0),
    .m_axi_gmem3_RLAST(1'b0),
    .m_axi_gmem3_RID(1'd0),
    .m_axi_gmem3_RFIFONUM(11'd0),
    .m_axi_gmem3_RUSER(1'd0),
    .m_axi_gmem3_RRESP(2'd0),
    .m_axi_gmem3_BVALID(gmem3_BVALID),
    .m_axi_gmem3_BREADY(xfMat2Array_8_0_64_64_1_2_1_1_U0_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(gmem3_BRESP),
    .m_axi_gmem3_BID(gmem3_BID),
    .m_axi_gmem3_BUSER(gmem3_BUSER),
    .dstPtr_dout(img_out2_c_dout),
    .dstPtr_num_data_valid(img_out2_c_num_data_valid),
    .dstPtr_fifo_cap(img_out2_c_fifo_cap),
    .dstPtr_empty_n(img_out2_c_empty_n),
    .dstPtr_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_dstPtr_read)
);

sobel_resize_accel_fifo_w64_d6_S img_out1_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc13_U0_img_out1_c_din),
    .if_full_n(img_out1_c_full_n),
    .if_write(entry_proc13_U0_img_out1_c_write),
    .if_dout(img_out1_c_dout),
    .if_num_data_valid(img_out1_c_num_data_valid),
    .if_fifo_cap(img_out1_c_fifo_cap),
    .if_empty_n(img_out1_c_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_U0_dstPtr_read)
);

sobel_resize_accel_fifo_w64_d6_S img_out2_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc13_U0_img_out2_c_din),
    .if_full_n(img_out2_c_full_n),
    .if_write(entry_proc13_U0_img_out2_c_write),
    .if_dout(img_out2_c_dout),
    .if_num_data_valid(img_out2_c_num_data_valid),
    .if_fifo_cap(img_out2_c_fifo_cap),
    .if_empty_n(img_out2_c_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_dstPtr_read)
);

sobel_resize_accel_fifo_w32_d2_S_x in_mat_rows_c15_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_0),
    .if_full_n(in_mat_rows_c15_channel_full_n),
    .if_write(ap_channel_done_in_mat_rows_c15_channel),
    .if_dout(in_mat_rows_c15_channel_dout),
    .if_num_data_valid(in_mat_rows_c15_channel_num_data_valid),
    .if_fifo_cap(in_mat_rows_c15_channel_fifo_cap),
    .if_empty_n(in_mat_rows_c15_channel_empty_n),
    .if_read(Array2xfMat_8_0_128_128_1_2_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d2_S_x in_mat_cols_c16_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_1),
    .if_full_n(in_mat_cols_c16_channel_full_n),
    .if_write(ap_channel_done_in_mat_cols_c16_channel),
    .if_dout(in_mat_cols_c16_channel_dout),
    .if_num_data_valid(in_mat_cols_c16_channel_num_data_valid),
    .if_fifo_cap(in_mat_cols_c16_channel_fifo_cap),
    .if_empty_n(in_mat_cols_c16_channel_empty_n),
    .if_read(Array2xfMat_8_0_128_128_1_2_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d3_S_x0 out_resize_mat_rows_c17_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_2),
    .if_full_n(out_resize_mat_rows_c17_channel_full_n),
    .if_write(ap_channel_done_out_resize_mat_rows_c17_channel),
    .if_dout(out_resize_mat_rows_c17_channel_dout),
    .if_num_data_valid(out_resize_mat_rows_c17_channel_num_data_valid),
    .if_fifo_cap(out_resize_mat_rows_c17_channel_fifo_cap),
    .if_empty_n(out_resize_mat_rows_c17_channel_empty_n),
    .if_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d3_S_x0 out_resize_mat_cols_c18_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry1_proc_U0_ap_return_3),
    .if_full_n(out_resize_mat_cols_c18_channel_full_n),
    .if_write(ap_channel_done_out_resize_mat_cols_c18_channel),
    .if_dout(out_resize_mat_cols_c18_channel_dout),
    .if_num_data_valid(out_resize_mat_cols_c18_channel_num_data_valid),
    .if_fifo_cap(out_resize_mat_cols_c18_channel_fifo_cap),
    .if_empty_n(out_resize_mat_cols_c18_channel_empty_n),
    .if_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_ready)
);

sobel_resize_accel_fifo_w8_d2_S_x0 in_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_din),
    .if_full_n(in_mat_data_full_n),
    .if_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_data_write),
    .if_dout(in_mat_data_dout),
    .if_num_data_valid(in_mat_data_num_data_valid),
    .if_fifo_cap(in_mat_data_fifo_cap),
    .if_empty_n(in_mat_data_empty_n),
    .if_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_in_mat_data_read)
);

sobel_resize_accel_fifo_w32_d2_S_x in_mat_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_din),
    .if_full_n(in_mat_rows_c_full_n),
    .if_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_rows_c_write),
    .if_dout(in_mat_rows_c_dout),
    .if_num_data_valid(in_mat_rows_c_num_data_valid),
    .if_fifo_cap(in_mat_rows_c_fifo_cap),
    .if_empty_n(in_mat_rows_c_empty_n),
    .if_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_rows_read)
);

sobel_resize_accel_fifo_w32_d2_S_x in_mat_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_din),
    .if_full_n(in_mat_cols_c_full_n),
    .if_write(Array2xfMat_8_0_128_128_1_2_U0_in_mat_cols_c_write),
    .if_dout(in_mat_cols_c_dout),
    .if_num_data_valid(in_mat_cols_c_num_data_valid),
    .if_fifo_cap(in_mat_cols_c_fifo_cap),
    .if_empty_n(in_mat_cols_c_empty_n),
    .if_read(resize_1_0_128_128_64_64_1_false_2_2_2_U0_p_src_cols_read)
);

sobel_resize_accel_fifo_w8_d2_S_x0 out_resize_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_din),
    .if_full_n(out_resize_mat_data_full_n),
    .if_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_data_write),
    .if_dout(out_resize_mat_data_dout),
    .if_num_data_valid(out_resize_mat_data_num_data_valid),
    .if_fifo_cap(out_resize_mat_data_fifo_cap),
    .if_empty_n(out_resize_mat_data_empty_n),
    .if_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_out_resize_mat_data_read)
);

sobel_resize_accel_fifo_w32_d2_S_x out_resize_mat_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_din),
    .if_full_n(out_resize_mat_rows_c_full_n),
    .if_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_rows_c_write),
    .if_dout(out_resize_mat_rows_c_dout),
    .if_num_data_valid(out_resize_mat_rows_c_num_data_valid),
    .if_fifo_cap(out_resize_mat_rows_c_fifo_cap),
    .if_empty_n(out_resize_mat_rows_c_empty_n),
    .if_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_rows_read)
);

sobel_resize_accel_fifo_w32_d2_S_x out_resize_mat_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_din),
    .if_full_n(out_resize_mat_cols_c_full_n),
    .if_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_out_resize_mat_cols_c_write),
    .if_dout(out_resize_mat_cols_c_dout),
    .if_num_data_valid(out_resize_mat_cols_c_num_data_valid),
    .if_fifo_cap(out_resize_mat_cols_c_fifo_cap),
    .if_empty_n(out_resize_mat_cols_c_empty_n),
    .if_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_src_mat_cols_read)
);

sobel_resize_accel_fifo_w32_d5_S p_dstgx_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry14_proc_U0_ap_return_0),
    .if_full_n(p_dstgx_rows_channel_full_n),
    .if_write(ap_channel_done_p_dstgx_rows_channel),
    .if_dout(p_dstgx_rows_channel_dout),
    .if_num_data_valid(p_dstgx_rows_channel_num_data_valid),
    .if_fifo_cap(p_dstgx_rows_channel_fifo_cap),
    .if_empty_n(p_dstgx_rows_channel_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d5_S p_dstgx_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry14_proc_U0_ap_return_1),
    .if_full_n(p_dstgx_cols_channel_full_n),
    .if_write(ap_channel_done_p_dstgx_cols_channel),
    .if_dout(p_dstgx_cols_channel_dout),
    .if_num_data_valid(p_dstgx_cols_channel_num_data_valid),
    .if_fifo_cap(p_dstgx_cols_channel_fifo_cap),
    .if_empty_n(p_dstgx_cols_channel_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d5_S p_dstgy_rows_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry14_proc_U0_ap_return_2),
    .if_full_n(p_dstgy_rows_channel_full_n),
    .if_write(ap_channel_done_p_dstgy_rows_channel),
    .if_dout(p_dstgy_rows_channel_dout),
    .if_num_data_valid(p_dstgy_rows_channel_num_data_valid),
    .if_fifo_cap(p_dstgy_rows_channel_fifo_cap),
    .if_empty_n(p_dstgy_rows_channel_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_ready)
);

sobel_resize_accel_fifo_w32_d5_S p_dstgy_cols_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_entry14_proc_U0_ap_return_3),
    .if_full_n(p_dstgy_cols_channel_full_n),
    .if_write(ap_channel_done_p_dstgy_cols_channel),
    .if_dout(p_dstgy_cols_channel_dout),
    .if_num_data_valid(p_dstgy_cols_channel_num_data_valid),
    .if_fifo_cap(p_dstgy_cols_channel_fifo_cap),
    .if_empty_n(p_dstgy_cols_channel_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_ready)
);

sobel_resize_accel_fifo_w8_d2_S_x0 p_dstgx_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_din),
    .if_full_n(p_dstgx_data_full_n),
    .if_write(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgx_data_write),
    .if_dout(p_dstgx_data_dout),
    .if_num_data_valid(p_dstgx_data_num_data_valid),
    .if_fifo_cap(p_dstgx_data_fifo_cap),
    .if_empty_n(p_dstgx_data_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_U0_p_dstgx_data_read)
);

sobel_resize_accel_fifo_w8_d2_S_x0 p_dstgy_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_din),
    .if_full_n(p_dstgy_data_full_n),
    .if_write(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_p_dstgy_data_write),
    .if_dout(p_dstgy_data_dout),
    .if_num_data_valid(p_dstgy_data_num_data_valid),
    .if_fifo_cap(p_dstgy_data_fifo_cap),
    .if_empty_n(p_dstgy_data_empty_n),
    .if_read(xfMat2Array_8_0_64_64_1_2_1_1_U0_p_dstgy_data_read)
);

sobel_resize_accel_start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0 start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_din),
    .if_full_n(start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_full_n),
    .if_write(resize_1_0_128_128_64_64_1_false_2_2_2_U0_start_write),
    .if_dout(start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_dout),
    .if_empty_n(start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_empty_n),
    .if_read(Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready <= ap_sync_Array2xfMat_8_0_128_128_1_2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry14_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry14_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry14_proc_U0_ap_ready <= ap_sync_Block_entry14_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_entry1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_entry1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_entry1_proc_U0_ap_ready <= ap_sync_Block_entry1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_in_mat_cols_c16_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_in_mat_cols_c16_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_in_mat_cols_c16_channel <= ap_sync_channel_write_in_mat_cols_c16_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_in_mat_rows_c15_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_in_mat_rows_c15_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_in_mat_rows_c15_channel <= ap_sync_channel_write_in_mat_rows_c15_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel <= ap_sync_channel_write_out_resize_mat_cols_c18_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel <= 1'b0;
    end else begin
        if (((Block_entry1_proc_U0_ap_done & Block_entry1_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel <= ap_sync_channel_write_out_resize_mat_rows_c17_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_dstgx_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry14_proc_U0_ap_done & Block_entry14_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_dstgx_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_dstgx_cols_channel <= ap_sync_channel_write_p_dstgx_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_dstgx_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry14_proc_U0_ap_done & Block_entry14_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_dstgx_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_dstgx_rows_channel <= ap_sync_channel_write_p_dstgx_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_dstgy_cols_channel <= 1'b0;
    end else begin
        if (((Block_entry14_proc_U0_ap_done & Block_entry14_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_dstgy_cols_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_dstgy_cols_channel <= ap_sync_channel_write_p_dstgy_cols_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_dstgy_rows_channel <= 1'b0;
    end else begin
        if (((Block_entry14_proc_U0_ap_done & Block_entry14_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_dstgy_rows_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_dstgy_rows_channel <= ap_sync_channel_write_p_dstgy_rows_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc13_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc13_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc13_U0_ap_ready <= ap_sync_entry_proc13_U0_ap_ready;
        end
    end
end

assign Array2xfMat_8_0_128_128_1_2_U0_ap_continue = 1'b1;

assign Array2xfMat_8_0_128_128_1_2_U0_ap_start = (in_mat_rows_c15_channel_empty_n & in_mat_cols_c16_channel_empty_n & (ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_entry14_proc_U0_ap_continue = (ap_sync_channel_write_p_dstgy_rows_channel & ap_sync_channel_write_p_dstgy_cols_channel & ap_sync_channel_write_p_dstgx_rows_channel & ap_sync_channel_write_p_dstgx_cols_channel);

assign Block_entry14_proc_U0_ap_start = ((ap_sync_reg_Block_entry14_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_entry1_proc_U0_ap_continue = (ap_sync_channel_write_out_resize_mat_rows_c17_channel & ap_sync_channel_write_out_resize_mat_cols_c18_channel & ap_sync_channel_write_in_mat_rows_c15_channel & ap_sync_channel_write_in_mat_cols_c16_channel);

assign Block_entry1_proc_U0_ap_start = ((ap_sync_reg_Block_entry1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_continue = 1'b1;

assign Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_start = start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_empty_n;

assign ap_channel_done_in_mat_cols_c16_channel = ((ap_sync_reg_channel_write_in_mat_cols_c16_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_in_mat_rows_c15_channel = ((ap_sync_reg_channel_write_in_mat_rows_c15_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_out_resize_mat_cols_c18_channel = ((ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_out_resize_mat_rows_c17_channel = ((ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel ^ 1'b1) & Block_entry1_proc_U0_ap_done);

assign ap_channel_done_p_dstgx_cols_channel = ((ap_sync_reg_channel_write_p_dstgx_cols_channel ^ 1'b1) & Block_entry14_proc_U0_ap_done);

assign ap_channel_done_p_dstgx_rows_channel = ((ap_sync_reg_channel_write_p_dstgx_rows_channel ^ 1'b1) & Block_entry14_proc_U0_ap_done);

assign ap_channel_done_p_dstgy_cols_channel = ((ap_sync_reg_channel_write_p_dstgy_cols_channel ^ 1'b1) & Block_entry14_proc_U0_ap_done);

assign ap_channel_done_p_dstgy_rows_channel = ((ap_sync_reg_channel_write_p_dstgy_rows_channel ^ 1'b1) & Block_entry14_proc_U0_ap_done);

assign ap_done = ap_sync_done;

assign ap_idle = (xfMat2Array_8_0_64_64_1_2_1_U0_ap_idle & xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_idle & resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_idle & (out_resize_mat_cols_c18_channel_empty_n ^ 1'b1) & (out_resize_mat_rows_c17_channel_empty_n ^ 1'b1) & (in_mat_cols_c16_channel_empty_n ^ 1'b1) & (in_mat_rows_c15_channel_empty_n ^ 1'b1) & (p_dstgy_cols_channel_empty_n ^ 1'b1) & (p_dstgy_rows_channel_empty_n ^ 1'b1) & (p_dstgx_cols_channel_empty_n ^ 1'b1) & (p_dstgx_rows_channel_empty_n ^ 1'b1) & entry_proc13_U0_ap_idle & Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_ap_idle & Block_entry1_proc_U0_ap_idle & Block_entry14_proc_U0_ap_idle & Array2xfMat_8_0_128_128_1_2_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Array2xfMat_8_0_128_128_1_2_U0_ap_ready = (ap_sync_reg_Array2xfMat_8_0_128_128_1_2_U0_ap_ready | Array2xfMat_8_0_128_128_1_2_U0_ap_ready);

assign ap_sync_Block_entry14_proc_U0_ap_ready = (ap_sync_reg_Block_entry14_proc_U0_ap_ready | Block_entry14_proc_U0_ap_ready);

assign ap_sync_Block_entry1_proc_U0_ap_ready = (ap_sync_reg_Block_entry1_proc_U0_ap_ready | Block_entry1_proc_U0_ap_ready);

assign ap_sync_channel_write_in_mat_cols_c16_channel = ((in_mat_cols_c16_channel_full_n & ap_channel_done_in_mat_cols_c16_channel) | ap_sync_reg_channel_write_in_mat_cols_c16_channel);

assign ap_sync_channel_write_in_mat_rows_c15_channel = ((in_mat_rows_c15_channel_full_n & ap_channel_done_in_mat_rows_c15_channel) | ap_sync_reg_channel_write_in_mat_rows_c15_channel);

assign ap_sync_channel_write_out_resize_mat_cols_c18_channel = ((out_resize_mat_cols_c18_channel_full_n & ap_channel_done_out_resize_mat_cols_c18_channel) | ap_sync_reg_channel_write_out_resize_mat_cols_c18_channel);

assign ap_sync_channel_write_out_resize_mat_rows_c17_channel = ((out_resize_mat_rows_c17_channel_full_n & ap_channel_done_out_resize_mat_rows_c17_channel) | ap_sync_reg_channel_write_out_resize_mat_rows_c17_channel);

assign ap_sync_channel_write_p_dstgx_cols_channel = ((p_dstgx_cols_channel_full_n & ap_channel_done_p_dstgx_cols_channel) | ap_sync_reg_channel_write_p_dstgx_cols_channel);

assign ap_sync_channel_write_p_dstgx_rows_channel = ((p_dstgx_rows_channel_full_n & ap_channel_done_p_dstgx_rows_channel) | ap_sync_reg_channel_write_p_dstgx_rows_channel);

assign ap_sync_channel_write_p_dstgy_cols_channel = ((p_dstgy_cols_channel_full_n & ap_channel_done_p_dstgy_cols_channel) | ap_sync_reg_channel_write_p_dstgy_cols_channel);

assign ap_sync_channel_write_p_dstgy_rows_channel = ((p_dstgy_rows_channel_full_n & ap_channel_done_p_dstgy_rows_channel) | ap_sync_reg_channel_write_p_dstgy_rows_channel);

assign ap_sync_done = (xfMat2Array_8_0_64_64_1_2_1_U0_ap_done & xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_done);

assign ap_sync_entry_proc13_U0_ap_ready = (entry_proc13_U0_ap_ready | ap_sync_reg_entry_proc13_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc13_U0_ap_ready & ap_sync_Block_entry1_proc_U0_ap_ready & ap_sync_Block_entry14_proc_U0_ap_ready & ap_sync_Array2xfMat_8_0_128_128_1_2_U0_ap_ready);

assign entry_proc13_U0_ap_continue = 1'b1;

assign entry_proc13_U0_ap_start = ((ap_sync_reg_entry_proc13_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem1_RID = 1'd0;

assign gmem1_RLAST = 1'b0;

assign gmem1_RRESP = 2'd0;

assign gmem1_RUSER = 1'd0;

assign gmem2_BID = 1'd0;

assign gmem2_BRESP = 2'd0;

assign gmem2_BUSER = 1'd0;

assign gmem3_BID = 1'd0;

assign gmem3_BRESP = 2'd0;

assign gmem3_BUSER = 1'd0;

assign resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_continue = 1'b1;

assign resize_1_0_128_128_64_64_1_false_2_2_2_U0_ap_start = (out_resize_mat_rows_c17_channel_empty_n & out_resize_mat_cols_c18_channel_empty_n);

assign start_for_Sobel_0_3_0_0_64_64_1_false_2_2_2_U0_din = 1'b1;

assign xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_continue = ap_sync_done;

assign xfMat2Array_8_0_64_64_1_2_1_1_U0_ap_start = (p_dstgy_rows_channel_empty_n & p_dstgy_cols_channel_empty_n);

assign xfMat2Array_8_0_64_64_1_2_1_U0_ap_continue = ap_sync_done;

assign xfMat2Array_8_0_64_64_1_2_1_U0_ap_start = (p_dstgx_rows_channel_empty_n & p_dstgx_cols_channel_empty_n);


reg find_df_deadlock = 0;
// synthesis translate_off
`include "sobel_resize_accel_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //sobel_resize_accel

