#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Sat Jul 13 16:20:24 CST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : sobel.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : sobel.sh
#                sobel.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                sobel.sh [-reset_run]
#                sobel.sh [-reset_log]
#                sobel.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'sobel.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_15 -libname processing_system7_vip_v1_0_17 -libname lib_pkg_v1_0_3 -libname fifo_generator_v13_2_9 -libname lib_fifo_v1_0_18 -libname lib_srl_fifo_v1_0_3 -libname lib_cdc_v1_0_2 -libname axi_datamover_v5_1_31 -libname axi_sg_v4_1_17 -libname axi_dma_v7_1_30 -libname generic_baseblocks_v2_1_1 -libname axi_register_slice_v2_1_29 -libname axi_data_fifo_v2_1_28 -libname axi_crossbar_v2_1_30 -libname proc_sys_reset_v5_0_14 -libname axi_protocol_converter_v2_1_29 -libname axi_clock_converter_v2_1_28 -libname blk_mem_gen_v8_4_7 -libname axi_dwidth_converter_v2_1_29 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_15 processing_system7_vip_v1_0_17 lib_pkg_v1_0_3 fifo_generator_v13_2_9 lib_fifo_v1_0_18 lib_srl_fifo_v1_0_3 lib_cdc_v1_0_2 axi_datamover_v5_1_31 axi_sg_v4_1_17 axi_dma_v7_1_30 generic_baseblocks_v2_1_1 axi_register_slice_v2_1_29 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 proc_sys_reset_v5_0_14 axi_protocol_converter_v2_1_29 axi_clock_converter_v2_1_28 blk_mem_gen_v8_4_7 axi_dwidth_converter_v2_1_29)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "sobel.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./sobel.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/sxy/new-vol/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/sxy/new-vol/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/home/sxy/new-vol/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_CTRL_s_axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_flow_control_loop_pipe_sequential_init.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_hls_deadlock_idx0_monitor.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_hls_deadlock_idx2_monitor.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_LineBuffer_RAM_AUTO_1R1W.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_regslice_both.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_sobel_Pipeline_VITIS_LOOP_88_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_sobel_Pipeline_VITIS_LOOP_118_3.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_sparsemux_7_2_2_1_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel_sparsemux_7_2_8_1_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog/sobel.v" \
  "../../../bd/sobel/ip/sobel_sobel_0_0/sim/sobel_sobel_0_0.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_addrbound.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Array2xfMat_8_0_128_128_1_2_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Axi2AxiStream.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Axi2AxiStream_Pipeline_VITIS_LOOP_1021_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Axi2Mat.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_AxiStream2Axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_AxiStream2Axi_Pipeline_MMIterOutLoop2.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_AxiStream2Mat.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_AxiStream2MatStream_2_Pipeline_MMIterInLoopRow.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_AxiStream2MatStream_2_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Block_entry1_proc.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_control_s_axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_entry_proc.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_entry_proc9.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_entry_proc10.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_entry_proc11.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w4_d2_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w4_d2_S_x.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w8_d2_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w8_d2_S_x.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w8_d2_S_x0.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w15_d2_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w16_d3_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w32_d2_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w32_d2_S_x.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w32_d3_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w32_d3_S_x.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w32_d4_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w64_d4_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_fifo_w64_d5_S.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_flow_control_loop_pipe_sequential_init.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_gmem1_m_axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_gmem2_m_axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_gmem3_m_axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_hls_deadlock_detection_unit.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_last_blk_pxl_width.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_last_blk_pxl_width_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Mat2Axi.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Mat2Axi_Block_entry24_proc.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Mat2AxiStream.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_MatStream2AxiStream_2_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_mul_15s_15s_15_3_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_mul_16ns_16ns_32_1_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_mul_32s_32s_32_2_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_Sobel_0_3_0_0_128_128_1_false_2_2_2_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_sparsemux_7_2_8_1_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_sparsemux_7_13_2_1_1.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_start_for_AxiStream2Mat_U0.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_start_for_Sobel_0_3_0_0_128_128_1_false_2_2_2_U0.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFGradientX3x3_0_0_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFGradientY3x3_0_0_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xfMat2Array_8_0_128_128_1_2_1_2.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xfMat2Array_8_0_128_128_1_2_1_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFSobel3x3_1_1_0_0_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFSobelFilter3x3_0_0_128_128_1_0_0_1_2_2_2_1_1_128_false_s_buf_RAM_S2P_BRAM_1bkb.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFSobelFilter3x3_Pipeline_Clear_Row_Loop.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel_xFSobelFilter3x3_Pipeline_Col_Loop.v" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog/sobel_accel.v" \
  "../../../bd/sobel/ip/sobel_sobel_accel_0_4/sim/sobel_sobel_accel_0_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_17 $xmvlog_opts -sv +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/sobel/ip/sobel_processing_system7_0_1/sim/sobel_processing_system7_0_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_18 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_31 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_sg_v4_1_17 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/1b4d/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_dma_v7_1_30 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ddec/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/sobel/ip/sobel_axi_dma_0_0/sim/sobel_axi_dma_0_0.vhd" \
  "../../../bd/sobel/ip/sobel_axi_dma_1_0/sim/sobel_axi_dma_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_28 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_30 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/sobel/ip/sobel_xbar_2/sim/sobel_xbar_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 -V93 $xmvhdl_opts \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/sobel/ip/sobel_rst_ps7_0_50M_2/sim/sobel_rst_ps7_0_50M_2.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/sobel/ip/sobel_xbar_3/sim/sobel_xbar_3.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/sobel/ip/sobel_auto_pc_0/sim/sobel_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_28 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/769c/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_dwidth_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/670d/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/827a/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/b972/hdl/verilog" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/ec67/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ipshared/6b2b/hdl" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_0_0/drivers/sobel_v1_0/src" +incdir+"../../../../Lab1_sobel.gen/sources_1/bd/sobel/ip/sobel_sobel_accel_0_4/drivers/sobel_accel_v1_0/src" +incdir+"/home/sxy/new-vol/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/sobel/ip/sobel_auto_us_0/sim/sobel_auto_us_0.v" \
  "../../../bd/sobel/ip/sobel_auto_us_1/sim/sobel_auto_us_1.v" \
  "../../../bd/sobel/ip/sobel_auto_us_2/sim/sobel_auto_us_2.v" \
  "../../../bd/sobel/ip/sobel_auto_us_3/sim/sobel_auto_us_3.v" \
  "../../../bd/sobel/ip/sobel_auto_us_4/sim/sobel_auto_us_4.v" \
  "../../../bd/sobel/ip/sobel_auto_pc_1/sim/sobel_auto_pc_1.v" \
  "../../../bd/sobel/sim/sobel.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.sobel xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.sobel -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path != "") && !(-e $lib_map_path) ]]; then
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log sobel_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./sobel.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: sobel.sh [-help]\n\
Usage: sobel.sh [-step]\n\
Usage: sobel.sh [-lib_map_path]\n\
Usage: sobel.sh [-reset_run]\n\
Usage: sobel.sh [-reset_log]\n\
Usage: sobel.sh [-keep_index]\n\
Usage: sobel.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
